import Login from "@/components/pages/login/Login";
export const metadata = {
    title: "Chat login ❤️",
    description: "Generated by create next app",
};
const page = () => {
    return <Login />;
};

export default page;
