import Login from "@/components/pages/login/Login";
import BgLogin from "@/components/pages/login/BgLogin";
export const metadata = {
    title: "Chat login ❤️",
    description: "Generated by create next app",
};
const page = () => {
    return (
        <BgLogin>
            <Login />
        </BgLogin>
    );
};

export default page;
