import localFont from "next/font/local";
import Header from "@/components/header/Header";
import AuthProvider from "@/authProvider/AuthProvider";
import "./globals.css";

const Playpen_Sans = localFont({ src: "../fonts/Playpen_Sans/PlaypenSans-VariableFont_wght.ttf" });

export const metadata = {
    title: "Chat jsx ❤️",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={Playpen_Sans.className}>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
