import Header from "@/components/header/Header";
export const metadata = {
    title: "Chat jsx - Search",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <section>
            <Header search />
            search
        </section>
    );
};

export default page;
